"""
Tests the transformation from debt events into customer messages.

The tests verify customer grouping, message preparation, payment information,
name presentation, and the responsibility transfer between both queues.
"""

from datetime import date

from src.dispatchers.message_dispatcher import MessageDispatcher
from src.models.collectible_debt import CollectibleDebt
from src.queue.debt_queue_item import DebtQueueItem
from src.queue.debt_queue_repository import DebtQueueRepository
from src.queue.message_queue_repository import MessageQueueRepository


def create_debt_queue_item(
    transaction_id: int,
    customer_id: int,
    customer_name: str,
    amount_cents: int,
    due_date: date,
    collection_day: int,
) -> DebtQueueItem:
    """Creates a debt event ready to be inserted into the first queue."""

    debt = CollectibleDebt(
        galaxpay_transaction_id=transaction_id,
        customer_id=customer_id,
        customer_name=customer_name,
        customer_phones=["5511999999999"],
        amount_cents=amount_cents,
        due_date=due_date,
        bank_line=f"BANK-LINE-{transaction_id}",
    )

    return DebtQueueItem(
        debt=debt,
        collection_day=collection_day,
        idempotency_key=f"{transaction_id}:{collection_day}",
    )


def print_generated_messages(message_items) -> None:
    """
    Displays the delivery instructions generated by the dispatcher.

    The greeting remains unresolved because it belongs to delivery-time context
    and will later be replaced by the MessagePerformer.
    """

    for message_item in message_items:
        print("\n" + "=" * 70)
        print(message_item.main_message)

        for charge in message_item.charges:
            print()
            print(charge.message)
            print(f"[COPY CODE] {charge.bank_line}")

        print("=" * 70)


def test_groups_debts_by_customer_and_prepares_messages(tmp_path):
    database_path = tmp_path / "test.db"

    debt_repository = DebtQueueRepository(str(database_path))
    message_repository = MessageQueueRepository(str(database_path))

    dispatcher = MessageDispatcher(
        debt_repository,
        message_repository,
    )

    # The full customer name remains part of the domain data. The dispatcher
    # should use only the first name in customer-facing communication.
    debt_repository.enqueue(
        create_debt_queue_item(
            transaction_id=1001,
            customer_id=501,
            customer_name="Luciano Alves dos Santos",
            amount_cents=100000,
            due_date=date(2026, 9, 11),
            collection_day=5,
        )
    )

    debt_repository.enqueue(
        create_debt_queue_item(
            transaction_id=1002,
            customer_id=501,
            customer_name="Luciano Alves dos Santos",
            amount_cents=50000,
            due_date=date(2026, 9, 21),
            collection_day=-5,
        )
    )

    # John belongs to another customer and must receive an independent message.
    debt_repository.enqueue(
        create_debt_queue_item(
            transaction_id=1003,
            customer_id=502,
            customer_name="John Michael Smith",
            amount_cents=25000,
            due_date=date(2026, 9, 16),
            collection_day=0,
        )
    )

    enqueued_count = dispatcher.dispatch()

    # Three debt events become two customer-level messages.
    assert enqueued_count == 2

    # Responsibility has moved to the second queue.
    assert debt_repository.get_pending_items() == []

    pending_messages = message_repository.get_pending_items()

    assert len(pending_messages) == 2

    print_generated_messages(pending_messages)

    luciano_message = next(
        item
        for item in pending_messages
        if "Luciano" in item.main_message
    )

    john_message = next(
        item
        for item in pending_messages
        if "John" in item.main_message
    )

    # Luciano's two debts are grouped into one message. Only his first name is
    # used and the greeting remains a delivery-time placeholder.
    assert luciano_message.main_message == (
        "{{greeting}}, Luciano.\n\n"
        "This message is regarding the following outstanding balances:"
    )

    assert "Alves dos Santos" not in luciano_message.main_message

    assert len(luciano_message.charges) == 2

    assert luciano_message.charges[0].message == (
        "Invoice of R$ 1,000.00 that was due on 09/11/2026. "
        "Here is the payment code:"
    )
    assert luciano_message.charges[0].bank_line == "BANK-LINE-1001"

    assert luciano_message.charges[1].message == (
        "Invoice of R$ 500.00 due on 09/21/2026. "
        "Here is the payment code:"
    )
    assert luciano_message.charges[1].bank_line == "BANK-LINE-1002"

    assert luciano_message.source_event_keys == [
        "1001:5",
        "1002:-5",
    ]

    # A customer with one debt receives singular wording.
    assert john_message.main_message == (
        "{{greeting}}, John.\n\n"
        "This message is regarding the following outstanding balance:"
    )

    assert "Michael Smith" not in john_message.main_message

    assert len(john_message.charges) == 1

    assert john_message.charges[0].message == (
        "Invoice of R$ 250.00 due today, 09/16/2026. "
        "Here is the payment code:"
    )
    assert john_message.charges[0].bank_line == "BANK-LINE-1003"

    assert john_message.source_event_keys == ["1003:0"]


def test_dispatching_again_does_not_create_duplicate_messages(tmp_path):
    database_path = tmp_path / "test.db"

    debt_repository = DebtQueueRepository(str(database_path))
    message_repository = MessageQueueRepository(str(database_path))

    dispatcher = MessageDispatcher(
        debt_repository,
        message_repository,
    )

    debt_repository.enqueue(
        create_debt_queue_item(
            transaction_id=2001,
            customer_id=601,
            customer_name="Sarah Elizabeth Wilson",
            amount_cents=75000,
            due_date=date(2026, 9, 11),
            collection_day=5,
        )
    )

    first_run = dispatcher.dispatch()
    second_run = dispatcher.dispatch()

    # After the first transfer there are no pending source events available
    # to generate the same customer communication again.
    assert first_run == 1
    assert second_run == 0

    pending_messages = message_repository.get_pending_items()

    assert len(pending_messages) == 1